version: '3.7'
services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: host
    env_file: 
      - .db.env
    volumes:
      - db_data:/var/lib/mysql
  ui:
    build:
      context: ../chess-ui
    ports:
      - target: 443
        published: 3000
        protocol: tcp
        mode: host
    depends_on:
      - api
  api:
    build:
      context: .
      network: host
    restart: always
    ports:
      - target: 8443
        published: 8443
        protocol: tcp
        mode: host
    depends_on:
      - db
    env_file: 
      - .env
volumes:
  db_data: {}